services:
  - type: web
    name: skin-disease-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: FAST2SMS_API_KEY
        sync: false
      - key: PORT
        value: 10000 